CXX=g++
CXXFLAGS=-I$(HOME)/include
CXXLIBS=-L$(HOME)/lib -lz -lpthread 
#BAMINC=-I/home/chenz11/include
#BAMLIB=-lhts -lbam
CPPFLAGS=-g
CPPLIBS=
bit2_seq.o: bit2_seq.cpp
	$(CXX) ${CXXFLAGS} ${CPPFLAGS} -c -fPIC $<
